### ISSUE TITLE
Add emotes functionality to /[staff name] chat pages

### ISSUE THREAD

**Issue by kodeyb** [lrkissling/giant-bomb-qol#71]
Doesn't seem to be working on /jeff, I might guess it isn't working on /vinny either.

**Comment by lrkissling** [comment]
Thanks for logging the issue.

**Comment by kmausolf** [comment]
This one is a bit difficult, given the way we're detecting chat pages.  The `chats` API does contain information for streams on different routes than `infinite` and `chat`, but not the URL of the stream.  Given these circumstances, we may be unable to detect such stream pages based on an API call or URL parse.  Now that the staff has taken to using the stream page template for routes other than `chat` or `infinite`, we may need to come up with another method of detecting these pages, or petition GB staff to include some metadata that would allow us to detect stream pages.

**Comment by lrkissling** [comment]
We will have to change the permissions in the manifest.json to load the
page script for all giant bomb pages instead of just /chat and /infinite,
since they can now put up a stream on any url. Then the first thing the
script will do is check for the existence of some element in the page that
indicates it's a stream page, and execute all the code if it is. Going to
try and do this tomorrow evening.

**Comment by lrkissling** [comment]
This has been resolved with 4.10.
