### ISSUE TITLE
Live stream notifications are incorrect?

### ISSUE THREAD

**Issue by alexxnz** [lrkissling/giant-bomb-qol#72]
I feel in the past few weeks, the Live Stream notifications have been showing incorrect information. Currently, I'm told there is a live stream going for Astroneer, but there is nothing being live streamed on the site.

If there is a live stream, the thumbnail/title is usually for the last game that was streamed, and not the current one.

I'm unsure if this is an API issue, or something on my end, but I figured I'd bring it up in case others are having the same issue.

**Comment by lrkissling** [comment]
Hi alexxnz, thanks for coming by with these issues you're having. These issues you are experiencing are unfortunately (since I can't fix them) due to the API results being returned by Giant Bomb. 

The dead Astroneer stream was due to Vinny not shutting down his giantbomb.com/vinny stream page after he was done streaming. And if you clicked on it, it directed you to giantbomb.com/chat because of a longstanding bug in the API that sets all stream urls to /chat. I [have notified GB devs of that bug](https://www.giantbomb.com/forums/bug-reporting-33/api-bug-site-detail-url-on-the-chats-endpoint-alwa-1881404/).

For these all-day quarantine streams, they appear to be setting the thumbnail and title for the /chat page once at the beginning of the day, and it usually corresponds to the first game streamed.

I hope you continue to enjoy using Giant Bomb QoL, and please feel free to bring forth any other issues or questions that come up!
